export const keywords = [
  "Color palette generator",
  "Extract colors from image",
  "Color extractor tool",
  "Image color palette",
  "Create color palettes",
  "Color picker from image",
  "Image to color palette",
  "Color scheme generator",
  "Image URL color extractor",
  "Color palette from URL",
  "Color palette creator",
  "Online color extractor",
  "Image color analyzer",
  "Digital design tool",
  "Color generator for design",
  "Extract dominant colors from image",
  "Custom color palette creator",
  "Color schemes for design",
];
